# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-23 08:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(help_text='Enter publish date', null=True, verbose_name='Publish Date')),
                ('raw_image', models.ImageField(blank=True, null=True, upload_to='thumbs/news/', verbose_name='News Image')),
                ('view_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Show', verbose_name='Related Show (Optional)')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NewsArticleTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='News Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='News Content')),
                ('master', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.NewsArticle')),
            ],
            options={
                'managed': True,
                'db_table': 'news_newsarticle_translation',
                'db_tablespace': '',
                'default_permissions': (),
                'verbose_name': 'News Article Translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='newsarticletranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
